service: apollo-server-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
